### ISSUE TITLE
建立连接存在失败的可能性

### ISSUE THREAD

**Issue by Keafmd** [rxf113/webrtc_web#9]
浏览器控制台显示，窗口被阻止。
A window.confirm() dialog generated by this page was suppressed because this page is not the active tab of the front window. Please make sure your dialogs are triggered by user interactions to avoid this situation. https://www.chromestatus.com/feature/5140698722467840

**Comment by rxf113** [comment]
是有这个情况 好像是浏览器的问题，改了，更新看看
